services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app_network
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080


networks:
  app_network:
    driver: bridge